taskmaster/urls.py
#############################################################################
# IMPORT STATEMENTS                                                         #
#############################################################################

from django.conf.urls import url,include
from django.urls import path
from taskmaster.views import *
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


#############################################################################
#URL Patterns                                                               #
#############################################################################
app_name = 'taskpg'

urlpatterns = [
                    url(r'^Task/$', taskpage,name="task_master"),
                    path('Task/<int:taskid>', show_task,name='show_task'),
                    path('Task/<int:taskid>/update', updatetaskpage,name='updatetask_page'),
                    path('command/<int:taskid>', command,name='command'),
                    url(r'^$', dashboard,name="dash_board"),
                    url(r'^note_show$', board_show_note,name="note_show"),
                    url(r'^note_update$', board_update_note,name="note_update"),
                    url(r'^timezone$', test_timezone,name="test_timezone"),
                    # The below URL is to create task with AJAX
                    url(r'^taskcreate/$', ajaxtaskcreate.as_view()),
                    # The below URL is to update the MY TASK CMD
                    url(r'^mytaskcmd/$', MY_TASK_CMD,name="my_task_cmd"),
                    # The below URL is to ALL TASKS
                    url(r'^alltask/$', alltask,name="alltask"),
                    # The below URL is for completed TASKS
                    url(r'^completedtask/$', completedtask,name="completedtask"),
              ]

web/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500
from commonpage.views import *
from taskmaster.views import *
from django.conf import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('commonpage.urls')),
    url(r'^',include('taskmaster.urls'))
]
handler404 = handler404_view
handler500 = handler500_view

templates/task/alltask.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load my_tag %}
{% block title %}
<title>Task Master</title>
<style media="screen">
  .dangerbtn
  {
    background-color: #F25F5C;
    color: white;
    border-radius: 20px;
  }
  .primarycol_btn
    {
      background-color: #537bb2;
      color: white;
      border-radius: 20px;
    }
</style>
{% endblock %}


{% block body %}
<br>
       <div class="row">
            <div class="col">
            <h4 class="heading" style="color:#537bb2;">All Active Task..</h4>
            </div>
       </div>

<div style="padding:1%;" class="row">
  <table id="userTbl" class="bordered">
        <thead class="thead-dark">
          <tr>
            <input type="text" style="border-radius:0px;" class="search form-control" placeholder="What you looking for? Use this free text search">
          </tr>
          <tr>
            <th width="3%"  style="text-align:center;" scope="col">SID</th>
            <th width="30%" style="text-align:center;" scope="col">Task Title</th>
            <th width="7%"  style="text-align:center;" scope="col">Status</th>
            <th width="7%"  style="text-align:center;" scope="col">Priority</th>
            <th width="7%"  style="text-align:center;" scope="col">Task</th>
            <th width="30%" style="text-align:center;"scope="col">Comments</th>
            <th width="7%"  style="text-align:center;" scope="col">Team</th>
            <th width="7%"  style="text-align:center;" scope="col">Processer</th>
            <th width="15%"  style="text-align:center;" scope="col">Due Date</th>

          </tr>
        </thead>
        <tbody>
          {% for taskstd in alltask|dictsort:"taskid.duedate" %}
          <tr align="center">
            <td style="text-align:center;"><a href="/Task/{{taskstd.taskid.id}}">{{ taskstd.taskid.sid|upper }}</a></td>
            <td style="text-align:center;">{{ taskstd.taskid.task_title|title|truncatechars:50 }}</td>
            <td style="text-align:center;">
              <div class="container {{ taskstd.taskid.status }}">
                {{ taskstd.taskid.status }}
              </div>
            </td>
            <a href="#"></a>
            <td style="text-align:center;">{{ taskstd.taskid.priority }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.tasktype }}</td>
            <td style="text-align:center;">{{ taskstd.comments|truncatechars:50 }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.processingteam.name }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.processor.last_name }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.duedate|date:"M.dS" }}</td>

          </tr>
          {% endfor %}

        </tbody>
    </table>
  <script type="text/javascript" src="{% static "js/tablesearch.js"%}"></script>
</div>

{% endblock %}

templates/task/commands.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_tag %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <style media="screen">
        ::-webkit-scrollbar {
          width: 15px;
          height: 15px;
          }
          ::-webkit-scrollbar-track-piece  {
          background-color: transprand;
          border-radius: 30px;
          }
          ::-webkit-scrollbar-thumb:vertical {
          height: 30px;
          background-color: transprand;
          border-radius: 30px;
          }
    </style> -->
    <link rel="stylesheet" href="{% static "/css/mycustom.css"%}">
  </head>
  <body>

    <div style="overflow-y: scroll; border:none; height: 445px;" class="col l12">
      {% for commd in commnd_list reversed %}
       <div class="col s12 m7 l12">
            <div class="card horizontal">
             <div class="card-stacked">
        <div style="padding:0px;background-color:#537bb2;color:white; " class="card-action">
          <div class="col s6"><p> {{ commd.updatedby.last_name|title }}</p></div>
          <div class="col s6"><p style="text-align:right;">{{commd.updateddate|date:"jS F Y h:i T"}}</p></div>
        </div>
        <div class="card-content">
          <span class="title">{{commd.comments}}</span>
        </div>
      </div>
      </div>
      </div>
      {% endfor %}
    </div>
  </body>
</html>

templates/task/completed_task.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load my_tag %}
{% block title %}
<title>Task Master</title>
<style media="screen">
  .dangerbtn
  {
    background-color: #F25F5C;
    color: white;
    border-radius: 20px;
  }
  .primarycol_btn
    {
      background-color: #537bb2;
      color: white;
      border-radius: 20px;
    }
</style>
{% endblock %}


{% block body %}
<br>
       <div class="row">
            <div class="col">
            <h4 class="display-3 heading" style="color:#537bb2;">Completed Task..</h4>
            </div>
       </div>
<br>
<div style="padding:1%;" class="row">
  <table id="userTbl" class="bordered">
        <thead class="thead-dark">
          <tr>
            <input type="text" style="border-radius:0px;" class="search form-control" placeholder="What you looking for? Use this free text search">
          </tr>
          <tr>
            <th width="3%"  style="text-align:center;" scope="col">SID</th>
            <th width="30%" style="text-align:center;" scope="col">Task Title</th>
            <th width="7%"  style="text-align:center;" scope="col">Status</th>
            <th width="7%"  style="text-align:center;" scope="col">Priority</th>
            <th width="7%"  style="text-align:center;" scope="col">Task</th>
            <th width="30%" style="text-align:center;"scope="col">Comments</th>
            <th width="7%"  style="text-align:center;" scope="col">Team</th>
            <th width="7%"  style="text-align:center;" scope="col">Processer</th>
            <th width="15%"  style="text-align:center;" scope="col">Due Date</th>

          </tr>
        </thead>
        <tbody>
          {% for taskstd in completedtask|dictsort:"taskid.duedate" %}
          <tr align="center">
            <td style="text-align:center;"><a href="/Task/{{taskstd.taskid.id}}">{{ taskstd.taskid.sid|upper }}</a></td>
            <td style="text-align:center;">{{ taskstd.taskid.task_title|title|truncatechars:50 }}</td>
            <td style="text-align:center;">
              <div class="container {{ taskstd.taskid.status }}">
                {{ taskstd.taskid.status }}
              </div>
            </td>
            <a href="#"></a>
            <td style="text-align:center;">{{ taskstd.taskid.priority }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.tasktype }}</td>
            <td style="text-align:center;">{{ taskstd.comments|truncatechars:50 }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.processingteam.name }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.processor.last_name }}</td>
            <td style="text-align:center;">{{ taskstd.taskid.duedate|date:"M.dS" }}</td>

          </tr>
          {% endfor %}

        </tbody>
    </table>
  <script type="text/javascript" src="{% static "js/tablesearch.js"%}"></script>
</div>

{% endblock %}

templates/task/task.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load my_tag %}
{% block title %}
<title>Task Master</title>
<style media="screen">
  .dangerbtn
  {
    background-color: #F25F5C;
    color: white;
    border-radius: 20px;
  }
  .primarycol_btn
    {
      background-color: #537bb2;
      color: white;
      border-radius: 20px;
    }
</style>
{% endblock %}


{% block body %}


<div style="display: none;" id="myDIV" class="container" >
        <br>
               <div class="row">
                    <div class="col">
                    <h4 class="display-3 heading" style="color:#537bb2;">Create Task..</h4>
                    </div>
               </div>
        <br>
        <form id="task_create" method="POST" action="." data-url='/taskcreate/' novalidate>
          {# {% csrf_token %} #}

              <div class="row">
                <div class="input-field col s12 m2 l1">
                    {{ form.sid }}
                  <label  for="sid">SID</label>
                </div>
                <div class="input-field col s12 m3 l2">
                  {{ form.datacenter }}
                <label for="sid">Data Center</label>
                </div>
                <div class="input-field col s12 m3 l2">
                  {{ form.priority }}
                <label for="sid">Priority</label>
                </div>
                <div class="input-field col s12 m3 l3">
                  {{ form.tasktype }}
                <label for="sid">Task Category</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12 m11 l8">
                    {{ form.task_title }}
                  <label for="task_title">Task Title</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12 m11 l8">
                    {{ form.task_description }}
                  <label for="task_description">Task Description</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12 m4 l3">
                    {{ form.sourceincident }}
                  <label for="first_name">Source Incident URL or NO</label>
                </div>
                <div class="input-field col s12 m3 l2">
                    {{ form.duedate }}
                  <label for="last_name">Due Date</label>
                </div>
                <div class="input-field col s12 m4 l3">
                  {{ form.processingteam }}
                <label for="last_name">Processing Team</label>
                </div>
              </div>

              <div class="row align-items-center">
                <div class="form-group col s6 m4 l2">
                  <button id="create_task" class="btn waves-effect waves-light primarycol_btn" type="submit" name="action">Submit</button>
                </div>


          </form>
          <div class="form-group col s6 m4 l">
            <a href="{% url 'taskpg:task_master' %}" class="waves-effect waves-light btn dangerbtn">Cancel</a>
          </div>
          </div>
        </div>

<br>

<div id="tab">
  <ul class="collapsible popout" data-collapsible="accordion">
        <li>
           <div class="collapsible-header"><i class="material-icons primarycol_alt">adb</i> <strong>Task with no processor</strong><span style="color:white;" class="badge myBadges">{{with_out_proc.count}}</span></div>
           <div class="collapsible-body">
             <table id="userTbl" class="bordered">
                   <thead class="thead-dark">
                     <tr>
                       <input type="text" style="border-radius:0px;" class="search form-control" placeholder="What you looking for? Use this free text search">
                     </tr>
                     <tr>
                       <th width="3%"  style="text-align:center;" scope="col">SID</th>
                       <th width="30%" style="text-align:center;" scope="col">Task Title</th>
                       <th width="7%"  style="text-align:center;" scope="col">Status</th>
                       <th width="7%"  style="text-align:center;" scope="col">Priority</th>
                       <th width="7%"  style="text-align:center;" scope="col">Task</th>
                       <th width="30%" style="text-align:center;"scope="col">Comments</th>
                       <th width="7%"  style="text-align:center;" scope="col">Processer</th>
                       <th width="15%"  style="text-align:center;" scope="col">Due Date</th>

                     </tr>
                   </thead>
                   <tbody>
                     {% for taskstd in with_out_proc %}
                     {# {% if taskstd.taskid.processor.is_active == False %} #}
                         <tr align="center">
                       <td style="text-align:center;"><a href="/Task/{{taskstd.taskid.id}}">{{ taskstd.taskid.sid|upper }}</a></td>
                       <td style="text-align:center;">{{ taskstd.taskid.task_title|truncatechars:50 }}</td>
                       <td style="text-align:center;">
                         <div class="container {{ taskstd.taskid.status }}">
                           {{ taskstd.taskid.status }}
                         </div>
                       </td>
                       <a href="#"></a>
                       <td style="text-align:center;">{{ taskstd.taskid.priority }}</td>
                       <td style="text-align:center;">{{ taskstd.taskid.tasktype }}</td>
                       <td style="text-align:center;">{{ taskstd.comments|truncatechars:50 }}</td>
                       <td style="text-align:center;">{{ taskstd.taskid.processor.last_name }}</td>
                       <td style="text-align:center;">{{ taskstd.taskid.duedate|date:"M.dS" }}</td>
                     </tr>
                     {# {% endif %} #}
                     {% endfor %}

                   </tbody>
               </table>
           </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons primarycol_alt">filter_drama</i> <strong>Task By Team</strong><span style="color:white;" class="badge myBadges">{{all_active_task.count}}</span></div>
            <div class="collapsible-body">
              <table id="userTbl" class="bordered">
                    <thead class="thead-dark">
                      <tr>
                        <input type="text" style="border-radius:0px;" class="search form-control" placeholder="What you looking for? Use this free text search">
                      </tr>
                      <tr>
                        <th width="3%"  style="text-align:center;" scope="col">SID</th>
                        <th width="30%" style="text-align:center;" scope="col">Task Title</th>
                        <th width="7%"  style="text-align:center;" scope="col">Status</th>
                        <th width="7%"  style="text-align:center;" scope="col">Priority</th>
                        <th width="7%"  style="text-align:center;" scope="col">Task</th>
                        <th width="30%" style="text-align:center;"scope="col">Comments</th>
                        <th width="7%"  style="text-align:center;" scope="col">Team</th>
                        <th width="7%"  style="text-align:center;" scope="col">Processer</th>
                        <th width="15%"  style="text-align:center;" scope="col">Due Date</th>

                      </tr>
                    </thead>
                    <tbody>
                      {% for taskstd in all_active_task|dictsort:"taskid.duedate" %}
                      <tr align="center">
                        <td style="text-align:center;"><a href="/Task/{{taskstd.taskid.id}}">{{ taskstd.taskid.sid|upper }}</a></td>
                        <td style="text-align:center;">{{ taskstd.taskid.task_title|title|truncatechars:50 }}</td>
                        <td style="text-align:center;">
                          <div class="container {{ taskstd.taskid.status }}">
                            {{ taskstd.taskid.status }}
                          </div>
                        </td>
                        <a href="#"></a>
                        <td style="text-align:center;">{{ taskstd.taskid.priority }}</td>
                        <td style="text-align:center;">{{ taskstd.taskid.tasktype }}</td>
                        <td style="text-align:center;">{{ taskstd.comments|truncatechars:50 }}</td>
                        <td style="text-align:center;">{{ taskstd.taskid.processingteam.name }}</td>
                        <td style="text-align:center;">{{ taskstd.taskid.processor.last_name }}</td>
                        <td style="text-align:center;">{{ taskstd.taskid.duedate|date:"M.dS" }}</td>

                      </tr>
                      {% endfor %}

                    </tbody>
                </table>
            </div>
           </li>
        {% for task in TaskTypeTag %}
        <li>
             <div class="collapsible-header"><i class="material-icons primarycol_alt">{{task.icon}}</i> <strong>{{task.tasktype}}</strong><span style="color:white;" class="badge myBadges">{{ task.id|find_count_BNG:user.groups.all.0.id }}</span></div>
             <div class="collapsible-body">
               <table id="userTbl" class="bordered">
                     <thead class="thead-dark">
                       <tr>
                         <input type="text" style="border-radius:0px;" class="search form-control" placeholder="What you looking for? Use this free text search">
                       </tr>
                       <tr>
                         <th width="3%"  style="text-align:center;" scope="col">SID</th>
                         <th width="30%" style="text-align:center;" scope="col">Task Title</th>
                         <th width="7%"  style="text-align:center;" scope="col">Status</th>
                         <th width="7%"  style="text-align:center;" scope="col">Priority</th>
                         <th width="7%"  style="text-align:center;" scope="col">Incident</th>
                         <th width="30%" style="text-align:center;"scope="col">Comments</th>
                         <th width="7%"  style="text-align:center;" scope="col">Processer</th>
                         <th width="15%"  style="text-align:center;" scope="col">Due Date</th>

                       </tr>
                     </thead>
                     <tbody>
                       {% for taskstd in all_active_task|dictsort:"taskid.duedate" %}
                            {% if task.id == taskstd.taskid.tasktype.id %}

                       <tr align="center">
                         <td style="text-align:center;"><a href="/Task/{{taskstd.taskid.id}}">{{ taskstd.taskid.sid|upper }}</a></td>
                         <td style="text-align:center;">{{ taskstd.taskid.task_title|truncatechars:50 }}</td>
                         <td style="text-align:center;">
                           <div class="container {{ taskstd.taskid.status }}">
                             {{ taskstd.taskid.status }}
                           </div>
                         </td>
                         <td style="text-align:center;">{{ taskstd.taskid.priority }}</td>
                         <td style="text-align:center;"><a href="{{ taskstd.taskid.sourceincident}}" target="_blank">{{ taskstd.taskid.sourceincident|is_incident }}</a></td>
                         <td style="text-align:center;">{{ taskstd.comments|truncatechars:50 }}</td>
                         <td style="text-align:center;">{{ taskstd.taskid.processor.last_name }}</td>
                         <td style="text-align:center;">{{ taskstd.taskid.duedate|date:"M.dS" }}</td>

                       </tr>
                            {% endif %}
                       {% endfor %}

                     </tbody>
                 </table>
             </div>
           </li>
        {% endfor %}
  </ul>

   <br>

   <div class="fixed-action-btn toolbar">
     <a class="btn-floating btn-large primarycol">
       <i class="large material-icons primarycol">mode_edit</i>
     </a>
     <ul>
       <li class="waves-effect waves-light primarycol"><a href="#!"><i class="material-icons">chat</i></a></li>
       <li class="waves-effect waves-light primarycol"><a href="{% url 'taskpg:completedtask' %}"><i class="material-icons">done_all</i></a></li>
       <li class="waves-effect waves-light primarycol"><a href="{% url 'taskpg:alltask' %}"><i class="material-icons">public</i></a></li>
       <li class="waves-effect waves-light primarycol"><a id="btn_show" href="#"><i class="material-icons">loupe</i></a></li>
     </ul>
   </div>

</div>

<script type="text/javascript" src="{% static "js/taskpage.js"%}"></script>
<script type="text/javascript" src="{% static "js/tablesearch.js"%}"></script>
{% endblock %}

templates/task/updatetask.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% load my_tag %}
{% block title %}
<title>Update Task</title>
<style>
.dangerbtn
  {
    background-color: #F25F5C;
    color: white;
  }
</style>

{% endblock %}


{% block body %}

<div>

   <div style="padding-left:2%;padding-right:1%;" class="row">
      {# The Text area #}
      <div class="row s12 m10 l6">
        <h5 class="heading" style="color:#537bb2;">Update Task..</h5>
        <form id="task_create" method="POST">
            {% csrf_token %}

                <div class="row">
                  <div class="input-field col s12 m1 l1">
                      {{ form.sid }}
                    <label id="taskid" for={{ taskid.id}}>SID</label>
                  </div>
                  <div class="input-field col s12 m1 l1">
                    {{ form.datacenter }}
                  <label for="sid">Data Center</label>
                  </div>

                  <!-- Modal Structure -->
                    <div id="modal1" class="modal modal-fixed-footer">
                        <div class="modal-content">
                          <div class="row">
                            <div class="input-field col s12 m6 l6">
                              {{ form.status }}
                            <label for="sid">Status</label>
                            </div>
                            <div class="input-field col s12 m6 l6">
                              {{ form.processor }}
                            <label for="sid">Processor</label>
                            </div>
                          <div class="row">
                              <div class="input-field col s12 m2 l4">
                                  {{ form.pid }}
                                <label for="last_name">Process ID</label>
                              </div>
                              <div class="input-field col s12 m3 l4">
                                  {{ form.errorincident }}
                                <label for="last_name">Error Incident URL/No</label>
                              </div>
                            </div>
                        </div>
                        </div>
                        <div class="modal-footer">
                          <a id="update_task" style="border-radius:20px;" type="button" name="action" class="btn waves-effect waves-light primarycol">Save</a>
                        </div>

                    </div>
                  <!-- Modal Structure -->
                  <div class="input-field col s12 m2 l2">
                    {{ form.priority }}
                  <label for="last_name">Priority</label>
                  </div>
                  <div class="input-field col s12 m2 l2">
                    {{ form.tasktype }}
                  <label for="last_name">Task Category</label>
                  </div>
                  <div class="input-field col s12 m3 l3">
                      {{ form.sourceincident }}
                    <label for="first_name">Source Incident URL/No</label>
                  </div>

                  <div class="input-field col s12 m2 l2">
                    {{ form.duedate }}
                  <label for="last_name">Due Date</label>
                  </div>

                </div>
                <div class="row">
                  <div class="input-field col s12 m2 l6">
                      {{ form.task_title }}
                    <label for="task_title">Task Title</label>
                  </div>
                  <div class="input-field col s12 m2 l6">
                      {{ form.task_description }}
                    <label for="task_description">Task Description</label>
                  </div>
                </div>
                <div class="row">


                </div>

        </form>
        <div class="row">
                  <div class="form-group col s12 m1 l2">
                    <a href="#modal1" style="border-radius:20px;" class="btn waves-effect waves-light primarycol modal-trigger">Update Task / Show more</a>
                  </div>
                    <div class="row s12 m1 l2">
                      <a style="border-radius:20px;" class="btn waves-effect waves-light primarycol modal-trigger" href="#modal2">Add comment</a>
                    </div>
            </div>
      </div>
      {# The command area #}
      <div id="modal2" class="modal bottom-sheet">
          <div class="modal-content">
            <h4>Add your comments here</h4>
            <form id="update_form" method="POST">
                  {% csrf_token %}
              {{form_cmd.as_p}}
            </form>
          </div>
          <div style="padding:2%;">
            <a style="border-radius:20px;" id="btn_add_cmd" id="update_task" name="action"type="button" class="btn waves-effect waves-light primarycol">Update comments</a>
          </div>
      </div>
  </div>
      {# The command box from commands page #}
      <div class="row s12 m10 l6">
        <div id="command_div">
        <div class="container">
          <div style="margin-top:10%;" class="progress">
          <div class="indeterminate"></div>
          </div>
        </div>
        </div>
      </div>
      {# The command ends #}

</div>

<script type="text/javascript" src="{% static "js/updatepage.js"%}"></script>
{% endblock %}