commonpage/urls.py
#############################################################################
# IMPORT STATEMENTS                                                         #
#############################################################################

from django.conf.urls import url,include
from commonpage.views import *
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500
from django.contrib.staticfiles.urls import static
from web import settings
from django.contrib.auth.views import (
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)

#############################################################################
#URL Patterns                                                               #
#############################################################################
app_name = 'userpg'

urlpatterns = [
                url(r'^login/$', login,name="login"),
                url(r'^logout/$', auth_views.logout,{'next_page': '/user/login/'},name="logout"),
                url(r'^register/', register, name='register'),
                # url(r'^$', home,name="home"),
                url(r'^testing/$', test_view),
                url(r'^teamdetails/$',update_team, name='update_team'),
                url(r'^profile/$', view_profile, name='view_profile'),
                url(r'^reset-password/$', password_reset, {'template_name': 'registration/reset-password.html'}),
                url(r'^reset-password/done/$', password_reset_done,{'template_name': 'registration/reset-password-done.html'}, name='password_reset_done'),
                url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name='password_reset_confirm'),
                url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),

              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404_view
handler500 = handler500_view

taskmaster/urls.py
#############################################################################
# IMPORT STATEMENTS                                                         #
#############################################################################

from django.conf.urls import url,include
from django.urls import path
from taskmaster.views import *
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


#############################################################################
#URL Patterns                                                               #
#############################################################################
app_name = 'taskpg'

urlpatterns = [
                    url(r'^Task/$', taskpage,name="task_master"),
                    path('Task/<int:taskid>', show_task,name='show_task'),
                    path('Task/<int:taskid>/update', updatetaskpage,name='updatetask_page'),
                    path('command/<int:taskid>', command,name='command'),
                    url(r'^$', dashboard,name="dash_board"),
                    url(r'^note_show$', board_show_note,name="note_show"),
                    url(r'^note_update$', board_update_note,name="note_update"),
                    url(r'^timezone$', test_timezone,name="test_timezone"),
                    # The below URL is to create task with AJAX
                    url(r'^taskcreate/$', ajaxtaskcreate.as_view()),
                    # The below URL is to update the MY TASK CMD
                    url(r'^mytaskcmd/$', MY_TASK_CMD,name="my_task_cmd"),
                    # The below URL is to ALL TASKS
                    url(r'^alltask/$', alltask,name="alltask"),
                    # The below URL is for completed TASKS
                    url(r'^completedtask/$', completedtask,name="completedtask"),
              ]

web/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500
from commonpage.views import *
from taskmaster.views import *
from django.conf import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('commonpage.urls')),
    url(r'^',include('taskmaster.urls'))
]
handler404 = handler404_view
handler500 = handler500_view

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
  <html>
    <head>
      <link rel="shortcut icon" type="image/x-icon" href="{% static "/image/browicon.png"%}" />
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/css?family=Barlow|Open+Sans+Condensed:300|Cabin+Sketch|Comfortaa|Kite+One" rel="stylesheet">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import Jquery-->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css"%}"  media="screen,projection"/>
      <!--Import custom.css-->
      <link rel="stylesheet" href="{% static "/css/mycustom.css"%}">
      <style media="screen">
          ::-webkit-scrollbar {
            width: 1px;
            height: 1px;
            }
            ::-webkit-scrollbar-track-piece  {
            background-color: transprand;
            border-radius: 30px;
            }
            ::-webkit-scrollbar-thumb:vertical {
            height: 30px;
            background-color: transprand;
            border-radius: 30px;
            }
      </style>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      {% block title %}
      <title>Base</title>
      {% endblock %}

    </head>
    <!-- Static navbar -->
    <ul id="dropdown1" class="dropdown-content">
      <li><a href="{% url 'userpg:view_profile' %}">Profile</a></li>
      <li><a href="{% url 'userpg:logout' %}">Logout</a></li>
    </ul>
    <nav>
        <div class="nav-wrapper" style="background-color: #537bb2;">
          <a style="margin:-.1% 0% 0% 0%;" class="brand-logo" href="{% url 'taskpg:dash_board' %}">
             <img src="{% static "/image/opsicon.png"%}" width="30" height="30" class="d-inline-block align-top" alt="">
            OpsBoard
          </a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'taskpg:task_master' %}">Task</a></li>
            <li><a href="#">Shift Roster</a></li>
            <li><a href="#">Task Status</a></li>
            {% if user.is_authenticated %}
            <li><a class="dropdown-button" data-icon="images/opsicon.png" class="circle" href="#" data-activates="dropdown1">Hi {{ user.last_name }}<i class="material-icons right">arrow_drop_down</i></a></li>
            {% else %}
            <li><a href="{% url 'userpg:login' %}">Login</a></li>
            {% endif %}
          </ul>
          <ul id="mobile-demo" class="side-nav">
              <li><div class="user-view">
                <div class="background">
                  <img style="height:'100%';width:'auto';" src="{% static "/image/sidnavbg.jpg"%}">
                </div>
                <a href="#!user"><img class="circle" src="{% static "/image/profile/i326707.jpg"%}"></a>
                <a href="#!name"><span class="white-text name">{{ user.last_name|title }}</span></a>
                <a href="#!email"><span class="white-text email">{{ user.user_profile.position }}</span></a>
              </div></li>
              <li><a class="waves-effect" href="{% url 'taskpg:dash_board' %}">Home</a></li>
              <li><a class="waves-effect" href="{% url 'taskpg:task_master' %}">Task</a></li>
              <li><a class="waves-effect" href="#">Shift Roster</a></li>
              <li><a class="waves-effect" href="#">Task Status</a></li>
              <li><a class="waves-effect" href="{% url 'userpg:view_profile'%}">Profile</a></li>
              <li><a href="{% url 'userpg:logout'%}" class="waves-effect waves-light btn primarycol">Logout</a></li>
         </ul>
        </div>
      </nav>
    <!-- Static navbar -->
    <!-- Body start -->
    <body>

      {% block body %}
      <h1>Its from base class</h1>
      {% endblock%}




      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="{% static "js/materialize.min.js"%}"></script>
      <!--Importing custom jQuery-->
      <script type="text/javascript" src="{% static "js/home.js"%}"></script>
      <script type="text/javascript" src="{% static "js/ajaxtoken.js"%}"></script>
      <script type="text/javascript" src="{% static "js/ajaxcall.js"%}"></script>

    </body>
    <!-- Body end -->
  </html>